import type { LeadField } from './lead-fields.types';

/** Spec data only. The system fields as a fresh organization gets them from the API. */
export const SYSTEM_FIELDS: LeadField[] = [
  {
    id: '01a09ba3-fb90-77df-8287-868ebed93d7e',
    key: 'candidate',
    label: 'Contact',
    type: 'text',
    options: [],
    isRequired: true,
    isReadOnly: false,
    isSystem: true,
    position: 0,
  },
  {
    id: '01a09ba3-fb90-77df-8287-882a07b53987',
    key: 'product',
    label: 'Product',
    type: 'select',
    options: ['POS', 'PMS', 'Other'],
    isRequired: true,
    isReadOnly: false,
    isSystem: true,
    position: 1,
  },
  {
    id: '01a09ba3-fb90-77df-8287-8f00fc2175e7',
    key: 'source',
    label: 'Source',
    type: 'url',
    options: [],
    isRequired: true,
    isReadOnly: false,
    isSystem: true,
    position: 2,
  },
  {
    id: '01a09ba3-fb90-77df-8287-909be156e5b0',
    key: 'signal',
    label: 'What they said',
    type: 'long_text',
    options: [],
    isRequired: true,
    isReadOnly: false,
    isSystem: true,
    position: 3,
  },
  {
    id: '01a09ba3-fb90-77df-8287-96ac992014bf',
    key: 'whyLead',
    label: 'Why this is a lead',
    type: 'long_text',
    options: [],
    isRequired: true,
    isReadOnly: false,
    isSystem: true,
    position: 4,
  },
  {
    id: '01a09ba3-fb90-77df-8287-9f179196ebde',
    key: 'status',
    label: 'Status',
    type: 'select',
    options: ['new', 'contacted', 'qualified'],
    isRequired: false,
    isReadOnly: true,
    isSystem: true,
    position: 5,
  },
  {
    id: '01a09ba3-fb90-77df-8287-a28221104e03',
    key: 'receivedAt',
    label: 'Received',
    type: 'datetime',
    options: [],
    isRequired: false,
    isReadOnly: true,
    isSystem: true,
    position: 6,
  },
];

/** Spec data only. Custom fields of each writable type, after the system ones. */
export const CUSTOM_FIELDS: LeadField[] = [
  {
    id: '01a09ba4-6ee3-726a-803c-605a580b6f2c',
    key: 'dealSize',
    label: 'Deal size',
    type: 'number',
    options: [],
    isRequired: false,
    isReadOnly: false,
    isSystem: false,
    position: 7,
  },
  {
    // Gold was an option once. Leads that hold it keep it.
    id: '01a09ba4-70a9-77cd-8f7d-3c2fbc65d116',
    key: 'tier',
    label: 'Tier',
    type: 'select',
    options: ['Silver', 'Bronze'],
    isRequired: false,
    isReadOnly: false,
    isSystem: false,
    position: 8,
  },
  {
    id: '01a09ba4-7291-7bd4-a8f5-0d1e0c7d3b11',
    key: 'followUp',
    label: 'Follow up',
    type: 'date',
    options: [],
    isRequired: false,
    isReadOnly: false,
    isSystem: false,
    position: 9,
  },
];

export const ALL_FIELDS: LeadField[] = [...SYSTEM_FIELDS, ...CUSTOM_FIELDS];
